const USER_TYPES = {
  ADULT: "ADULT",
  KID: "KID",
  SENIOR_CITIZEN: "SENIOR_CITIZEN",
};

const STATIONS = {
  AIRPORT: "AIRPORT",
  CENTRAL: "CENTRAL",
};

const PRICING = {
  [STATIONS.AIRPORT]: {
    [STATIONS.CENTRAL]: {
      [USER_TYPES.ADULT]: 200,
      [USER_TYPES.KID]: 50,
      [USER_TYPES.SENIOR_CITIZEN]: 100,
    },
  },
  [STATIONS.CENTRAL]: {
    [STATIONS.AIRPORT]: {
      [USER_TYPES.ADULT]: 200,
      [USER_TYPES.KID]: 50,
      [USER_TYPES.SENIOR_CITIZEN]: 100,
    },
  },
};

const RETURN_DISCOUNT_PERCENTAGE = 50;
const SERVICE_CHARGE_PERCENTAGE = 2;
const DEFAULT_DISCOUNT_AMOUNT = 0;
const DEFAULT_SERVICE_CHARGE = 0;

module.exports = {
  USER_TYPES,
  STATIONS,
  PRICING,
  RETURN_DISCOUNT_PERCENTAGE,
  SERVICE_CHARGE_PERCENTAGE,
  DEFAULT_DISCOUNT_AMOUNT,
  DEFAULT_SERVICE_CHARGE,
};
